### ISSUE TITLE
move from color to chalk 

### ISSUE THREAD

**Issue by derberg** [asyncapi/nodejs-template#110]
#### Reason/Context
This happened https://twitter.com/derberq/status/1480814592204972033 and we should not use color.js long term.

#### Description
Just use `chalk` instead of `color`. It should be straightforward to refactor. Readme has clear instructions how to use this template, so easy to test it locally.

**Comment by Samridhi-98** [comment]
@derberg  I would like to work on it.

**Comment by derberg** [comment]
@Samridhi-98 please go ahead 🙏🏼

**Comment by smoya** [comment]
TBH I have some mixed feelings about moving to `chalk` because of this. I understand the damage the creator of `colors` made, but at the same time, I do have empathy for it. Especially after the actions GH made with its account.

Shouldn’t this be moved into a debate with the community before taking any decision? Kindly asking here what you all think.

cc some people @derberg @fmvilas @alequetzalli

**Comment by derberg** [comment]
well, once I get a PR to replace color it with chalk I approve and merge it immediately. My opinion on what happened with `colors` has nothing to do here really. What matters is that I maintain this project and I feel responsible for what my users use, so have a much different approach than the maintainer of `colors`. I do not want template users to be harmed by any of the dependencies that we use here. `Color` is totally unreliable and doesn't make sense to keep it here. 

But of course, we can in parallel have an open discussion in `community` repo if you want. If the outcome of this discussion is to bring `color` back in, then let's do it, but I doubt it.

**Comment by alequetzalli** [comment]
> TBH I have some mixed feelings about moving to `chalk` because of this. I understand the damage the creator of `colors` made, but at the same time, I do have empathy for it. Especially after the actions GH made with its account.
> 
> Shouldn’t this be moved into a debate with the community before taking any decision? Kindly asking here what you all think.
> 
> cc some people @derberg @fmvilas @alequetzalli

Hey @smoya, sorry my inbox was a mess when I got back from vacation and now finally saw this one 😅 .. Ok, I had to google a bit to understand what in the world everyone was talking about. To answer your question, I honestly have never used any NPM package like these before, so I can't provide user feedback. That said, I agree that submitting it to a vote via a GH discussion is a great way to make sure the entire community backs this up/agrees with this approach. 🙂👍🏽👍🏽
