### ISSUE TITLE
Support secured protocols

### ISSUE THREAD

**Issue by gvensan** [asyncapi/nodejs-template#141]
#### Reason/Context
When specifying secured protocol and endpoints in the _server_ section, code generation fails with the following error:

> Something went wrong:
> Error: Server "production" uses the mqtts protocol but this template only supports the following ones: amqp,mqtt,kafka,kafka-secure,ws.
>     at isServerProtocolSupported (/Users/xxx/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:104:11)
>     at module.exports.validateTemplateConfig (/Users/xxx/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:26:5)
>     at Generator.generate (/Users/xxx/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/lib/generator.js:185:5)
>     at /Users/xxx/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/cli.js:154:9
> 

In the asyncapi document, the server specification is as follows:

```
servers:
  production:
    url: "mqtts://xxx.yyy.cloud:8883"
    protocol: mqtts
```

Consider supporting the same protocols with security (TLS/SSL encrypted) - i.e., amqps, mqtts and wss.

This would help avoid manual updates to the common.yml file.

**Comment by derberg** [comment]
@gvensan what additional changes are you required to make?

**Comment by gvensan** [comment]
Sorry, if I was not clear in my ask.

Based on AsyncAPI 2.3.0, can we assume that the [servers](https://www.asyncapi.com/docs/getting-started/servers) support secured protocols like this (although this was not explicitly called out in the spec):
```
  public:
    url: ws.kraken.com
    protocol: wss
```

If this is true, the specification of any protocol with security (SSL/TLS) like mqtts, wss results in an error by the 'ag command' with nodejs-template. 

The error clearly says:
> Error: Server "production" uses the wss protocol but this template only supports the following ones: amqp,mqtt,kafka,kafka-secure,ws.

Re-reading the stack trace I believe this error is thrown from the AsycnAPI config validator code - is this the right way to specify secured server endpoints?

**Comment by derberg** [comment]
@gvensan thanks for a detailed explanation. I've never tested the template against `mqtts`. If you did it and it works well without any code changes, then please just open a PR to config https://github.com/asyncapi/nodejs-template/blob/master/package.json#L77 and probably readme https://github.com/asyncapi/nodejs-template#supported-protocols

**Comment by wandertaker** [comment]
Hi,
I looked into this issue. The underlying mqtt library is able to handle the mqtts protocol as well.
However, some minor changes in the code were necessary to prevent errors in the generator when mqtts is used in the AsyncAPI specification. Hope this solves your problem @gvensan.
