### ISSUE TITLE
AsyncAPI spec v3 support in Node.js template

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/nodejs-template#215]
#### Reason/Context
This Issue is used to track changes needed to support AsyncAPI v3. As a code owner, please edit this list of TODO tasks in order to properly track the progress 🙂 Once this issue is closed it means that v3 is now fully supported in this library.  

Remaining tasks:

- [ ] Update template to use parser v2, this is already supported by the [generator by changing the `apiVersion`](https://github.com/asyncapi/generator/blob/master/docs/configuration-file.md)

**Comment by lukas-mertens** [comment]
@derberg Any progress on this? I would like to start using AsyncAPI and it feels like it would be best to start with the new spec version right away, but it feels like most of the code generators are not compatible yet. Or is it still recommended to go with v2 of the spec?

**Comment by derberg** [comment]
v3 release done, and coincidence is that it also support asyncapi v3
https://github.com/asyncapi/nodejs-template/releases/tag/v3.0.0

anyway, if there are any issues, feel free to report them

**Comment by meteatamel** [comment]
Is v3 supported in nodejs-template? I get this error when I try:

```
 asyncapi generate fromTemplate email-service-3.0.yaml @asyncapi/nodejs-template -o email-service-3.0 -p server=test

┌  AsyncAPI Generator
Error: @asyncapi/nodejs-template template does not support AsyncAPI v3 documents, please checkout https://github.com/asyncapi/nodejs-template/issues/215
```

**Comment by derberg** [comment]
@meteatamel the latest AsyncAPI CLI release fixes the problem

**Comment by meteatamel** [comment]
Thanks @derberg, I tested and the code generation for Node.js works now with 3. 0

**Comment by derberg** [comment]
Great!!! Thanks for confirmation!

fyi @kaushik-rishi
