### ISSUE TITLE
Remove unnecessary semicolon from filters

### ISSUE THREAD

**Issue by derberg** [asyncapi/nodejs-template#26]
Remove unnecessary semicolons from:
- https://github.com/asyncapi/nodejs-template/blob/master/filters/all.js#L8
- https://github.com/asyncapi/nodejs-template/blob/master/filters/all.js#L23
- https://github.com/asyncapi/nodejs-template/blob/master/filters/all.js#L36
- https://github.com/asyncapi/nodejs-template/blob/master/filters/all.js#L51
- https://github.com/asyncapi/nodejs-template/blob/master/filters/all.js#L56
- https://github.com/asyncapi/nodejs-template/blob/master/filters/all.js#L96
- https://github.com/asyncapi/nodejs-template/blob/master/filters/all.js#L105
- https://github.com/asyncapi/nodejs-template/blob/master/filters/all.js#L111
- https://github.com/asyncapi/nodejs-template/blob/master/filters/all.js#L117
- https://github.com/asyncapi/nodejs-template/blob/master/filters/all.js#L123
- https://github.com/asyncapi/nodejs-template/blob/master/filters/all.js#L128
- https://github.com/asyncapi/nodejs-template/blob/master/filters/all.js#L154
- https://github.com/asyncapi/nodejs-template/blob/master/filters/all.js#L159
- https://github.com/asyncapi/nodejs-template/blob/master/filters/all.js#L207﻿

**Comment by jooaodanieel** [comment]
Can I take this one?

**Comment by derberg** [comment]
@jooaodanieel yes, please. Good luck and let me know if ya need some help
