### ISSUE TITLE
Create README for this template

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/nodejs-template#4]
Make sure we don't forget to include:

1. How to install it.
1. How to use it.
1. The params it supports.
1. The requirement of `operationId` on each operation (otherwise, the code would not work).
1. This README should serve as a template for the rest of the generator templates.

**Comment by derberg** [comment]
would be awesome to have a template of the readme for all repos for consistency reasons, especially template readmies

**Comment by fmvilas** [comment]
Good point. Added it to the description.

**Comment by derberg** [comment]
video on how to approach this issue https://youtu.be/Iqs_2BiNEEo?t=1265

**Comment by derberg** [comment]
last part of requirement, turning this readmy into a readme template, is covered by https://github.com/asyncapi/template-for-generator-templates/pull/1

**Comment by KhudaDad414** [comment]
I want to work on this. please assign it to me. I think there is a lot of things that I can learn by doing this.

**Comment by KhudaDad414** [comment]
And if possible, please provide some instructions about how to approach this issue.

**Comment by derberg** [comment]
@KhudaDad414 assigned. I think the best is to have a look at this PR where I added a readme for another nodejs template -> https://github.com/asyncapi/nodejs-ws-template/pull/53/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

Let me know if you need something more

**Comment by KhudaDad414** [comment]
@derberg thanks. I'll start working on this.
