### ISSUE TITLE
Having trouble get the publish handler to execute code

### ISSUE THREAD

**Issue by reselbob** [asyncapi/nodejs-template#44]
Hi:

I have run into two situations that might be issues. The **first is this:** when I have a channel defined in Async API like so:

```
channels:
  wisesayingNeeded:
    subscribe:
      operationId: onWiseSayingNeededSub
      message:
        $ref: "#/components/messages/wiseSayingNeeded"
    publish:
      operationId: onWiseSayingNeededPub
      message:
       $ref: "#/components/messages/wiseSayingNeeded"
```

I expect  that `onWiseSayingNeededSub` will handle messages that are coming off of my subscription to `wisesayingNeeded` while `onWiseSayingNeededPub` will intercept messages I publish to the topic, `wisesayingNeeded ` on the broker and will pass those messages on to handler code `onWiseSayingNeededPub` that I created within the generated code.

I generate the code. Here are the contents of the `routes/wisesayingNeeded` from the generated code:

```
const Router = require('hermesjs/lib/router');
const router = new Router();
const wisesayingNeededHandler = require('../handlers/wisesayingNeeded');
module.exports = router;

router.use('wisesayingNeeded', async (message, next) => {
  try {
    await wisesayingNeededHandler.onWiseSayingNeededPub({message});
    next();
  } catch (e) {
    next(e);
  }
});
router.useOutbound('wisesayingNeeded', async (message, next) => {
  try {
    await wisesayingNeededHandler.onWiseSayingNeededSub({message});
    next();
  } catch (e) {
    next(e);
  }
});
```
Notice please that `wisesayingNeededHandler.onWiseSayingNeededSub` is called by `router.useOutbound()`. This is confusing because the documentation for `router.useOutbound()` is as follows:

```
Use a middleware for outbound messages.
Params:
args – The topic you want to scope the middleware to. @param {Function|HermesRouter} …middlewares A function or HermesRouter to use as a middleware.
```

To my understanding an outbound message is one that is being published. Thus, in order for this to make sense, I had to change the generated file to the following:

```
const Router = require('hermesjs/lib/router');
const router = new Router();
const wisesayingNeededHandler = require('../handlers/wisesayingNeeded');
module.exports = router;

router.use('wisesayingNeeded', async (message, next) => {
  try {
    await wisesayingNeededHandler.onWiseSayingNeededSub({message});
    next();
  } catch (e) {
    next(e);
  }
});
router.useOutbound('wisesayingNeeded', async (message, next) => {
  try {
    await wisesayingNeededHandler.onWiseSayingNeededPub({message});
    next();
  } catch (e) {
    next(e);
  }
});
```

My modification makes sense because outbound messages (those that are being published) are now routed to `wisesayingNeededHandler.onWiseSayingNeededPub` and incoming messages, which I've assumed is routed according to `router.use('wisesayingNeeded', async (message, next) => {...}` are being sent to the the subscriber handler.

Tell me please, is the modification I made appropriate?

**The second issue** is that it seems that control flow is not being passed on to `router.useOutbound('wisesayingNeeded', async (message, next) => {...}` when I publish a message to the broker using an external client, or when I publish a reply to a subscribed message, like so:

```
handler.onWiseSayingNeededSub = async ({message}) => {
  console.log({subbedNeeded: message.payload});
  message.hermes.send('responding to a subscription message',message.headers, 'wisesayingSent');
};
```

The reply messages **are** getting picked up by the subscriber handler, but nothing in the publish handler.

Tell me please, what am I doing incorrectly? When should I expect control flow to be passed to the publisher handler, `wisesayingNeededHandler.onWiseSayingNeededPub()`?

Also, one last question. Is using `message.hermes.send('responding to a subscription message',message.headers, 'wisesayingSent');` the best way to rely to an incoming message?

Thanks in advance for reading this very long entry. Thanks in advance for any help you can provide.

**Comment by derberg** [comment]
@reselbob can you share your entire AsyncAPI file so it is easier to see what is wrong

**Comment by reselbob** [comment]
Here is the entire project @derberg https://github.com/reselbob/simpleasyncapi

The asynchapi.yaml is here: https://github.com/reselbob/simpleasyncapi/blob/main/gen/asyncapi.yaml

**Comment by derberg** [comment]
@reselbob I analized your case and I think the problem is connected with confusion around pub/sub semantics. This is common when there is a broker in the middle.

looking at 
```
channels:
  wisesayingNeeded:
    subscribe:
      operationId: onWiseSayingNeededSub
      message:
        $ref: "#/components/messages/wiseSayingNeeded"
    publish:
      operationId: onWiseSayingNeededPub
      message:
       $ref: "#/components/messages/wiseSayingNeeded"
```

`onWiseSayingNeededPub` should be invoked when you get a message from a broker. So your application should be subscribed to `wisesayingNeeded`

so when I call the broker from outside with `mqtt pub -t 'wisesayingNeeded' -h 'test.mosquitto.org' -m '{"id": "1"}'`, your service should react and `handler.onWiseSayingNeededPub` should be invoked. Maybe just call those operationIds differently if they are confusing for you. Have a look at proper naming here https://github.com/asyncapi/spec/blob/2.0.0/examples/2.0.0/streetlights.yml#L45-L47

**Comment by reselbob** [comment]
Let me review your response and run my code again. It's been a while @derberg. Then, I'll let you know my findings. Thank you for the attention.

**Comment by derberg** [comment]
@reselbob sorry 😓 we've been busy with getting stuff set with Linux Foundation

**Comment by reselbob** [comment]
Now that I've reviewed my code and run it a few times @derberg I can see the issue is still there. Let me make a short screencast video that demonstrates the issue so we can have a common experience to discuss. Give me a day or two to create the video.

**Comment by derberg** [comment]
@reselbob you mean your code behaves differently than I described it?

**Comment by reselbob** [comment]
>>onWiseSayingNeededPub should be invoked when you get a message from a broker. So your application should be subscribed to wisesayingNeeded

Actually, this `onWiseSayingNeededPub` does invoke when a message is coming in. This is the cause of my confusion. I am sorry for confusing you on my end.

Allow me to ask on my end, when will the handler that I assign to `subscribe:` be fired? If not when a message comes into the system via publication, then when?

Again, please excuse me for making things more confusing.

**Comment by derberg** [comment]
no worries man, publish/subscribe is commonly confusing here, things in AsyncAPI are not that easy as in OpenAPI where they deal just with one protocol and use case.

> Actually, this onWiseSayingNeededPub does invoke when a message is coming in. This is the cause of my confusion. I am sorry for confusing you on my end.

Yeah, just set less confusing operationId as you can see here in an example https://github.com/asyncapi/spec/blob/2.0.0/examples/2.0.0/streetlights.yml#L45-L47

> Allow me to ask on my end, when will the handler that I assign to subscribe: be fired? If not when a message comes into the system via publication, then when?

Your server might not only accept messages, users may not only publish to it, they might also be interested in the messages that your server produces. Have a look at this blog post https://www.asyncapi.com/blog/building-async-flight-notification-service. Monitor service (user) is super interested with Subscriber service and the messages that it produces. Monitor service   is also an example of service that is a producer and a consumer at the same time https://github.com/amadeus4dev/amadeus-async-flight-status/blob/main/monitor/asyncapi.yaml

**Comment by reselbob** [comment]
@derberg In terms of the generated code (Node.JS) I am still wondering when the `subscribe;` handler will fire. But, maybe the answer is right in front of me and I don't see it?

**Comment by derberg** [comment]
do you refer to your specific AsyncAPI document or in general? I'm not sure I follow

**Comment by reselbob** [comment]
In my example, I have yet to be able to get the handler defined by `operationId` to fire when executing a subscription like so:

`mqtt sub -t 'wisesayingNeeded' -h 'test.mosquitto.org' -v`.

When I execute the statement above, what is supposed to happen in the auto-generated code? Is the handler defined by the `operationId` for the `subscribe` attribute supposed to fire?

As I reflect, maybe it's still best for me to do a demonstration video of the issue. I am getting anxious that I am eating up an inappropriate amount of your precision time.

**Comment by derberg** [comment]
so looking at this `mqtt sub -t 'wisesayingNeeded' -h 'test.mosquitto.org' -v`

`mqtt` CLI tool is like a user, a client of your server, a consumer that wants to get messages that your server will send to `wisesayingNeeded` topic/channel. The subscription that you perform here is between the client and the broker, and nothing is going to happen on your server, no handler is going to be triggered. 

If after calling `mqtt sub -t 'wisesayingNeeded' -h 'test.mosquitto.org' -v` you want to start receiving some messages, in your server you need to implement a logic that does it, you can just write some function that sends out a random message ( that is aligned with your payload definition otherwise internal validation will stop it) to a broker every 5sec or so.

sample code you should put at the end of your generated `index.js`
```js
(function myLoop (i) {
  setTimeout(() => {
    app.send({id: '1'}, {}, 'wisesayingNeeded');   
    if (--i) myLoop(i);
  }, 1000);
}(3));  
```

In `onWiseSayingNeededSub` handler you put additional middleware logic that does something to the message before it is sent. 

I tried your yaml file with nodejs template and above loop, all good. I only opened one PR to fix logging errors when validation see broken message -> https://github.com/asyncapi/nodejs-template/pull/59

**Comment by derberg** [comment]
@reselbob did my answer help you out?

**Comment by reselbob** [comment]
It might. I've been distracted attending to some deadlines. I need to refocus my attention soon so that I can confirm that I know how to make sure that I know how to bind message emission (publishing) from the message broker to the handler function defined as the `publish.operationId value` in the AsyncApi YAML and also bind message consumption behavior (subscription) in the message broker to the handler function defined in the `subscribe.operationId` attribute in the AsyncApi YAML file.

I really appreciate all the attention you are giving me.

**Comment by derberg** [comment]
no worries, let me know once you jump into the topic again and need some help. Up to you if you want to keep this issue opened or close and then reopen. Whatever is better for you.

**Comment by derberg** [comment]
Not sure what stage are you know with this challenge and if my answers helped. I'll close this issue for now and just reopen if you need more help
