### ISSUE TITLE
Kafka broker details missing from config

### ISSUE THREAD

**Issue by lornajane** [asyncapi/nodejs-template#66]
#### Describe the bug
When I generate from an asyncapi description for Kafka, the `config/common.yml` file has this empty entry for the broker:

```
broker:
```

This isn't correct! My broker is `localhost:9092`, the same as the default that's used.

#### How to Reproduce
Here's my asyncapi spec:

```
asyncapi: '2.0.0'
id: 'urn:com.github.aiven.thingum'
info:
  title: Thingum Industries Sensors 2
  description: Keeping the factory secure
  version: 1.0.0
  contact:
    name: Lorna
    email: lornajane@aiven.io
    url: https://github.com/aiven/thingum-industries
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  development:
    url: localhost:9092
    protocol: kafka
    protocolVersion: '1.0.0'

channels:
  door-sensor:
    description: Door sensors (external and internal)
    publish:
      operationId: DoorSensor
      summary: Open/closed state information from the doors.
      tags:
        - name: sensor
      bindings:
        kafka:
          clientId:
            type: string
      message:
        name: door-sensor-data
        title: Door Sensor Reading
        description: Door sensor data
        payload: 
          type: object
          properties:
            location:
              type: string
            state:
              enum: ["open", "closed"]

tags:
  - name: sensor
    description: Factory sensors
```

And the command I used to generate the code:

```
node cli.js asyncapi.yaml @asyncapi/nodejs-template -o nodejs-consumer -p server=development --force-write
```

#### Expected behavior
The `url` in the `servers` block would be used in the config for my generated client.

What happens instead is that here https://github.com/asyncapi/nodejs-template/blob/master/template/config/common.yml#L41 it gets passed through a `host` filter BUT since this URL does not have a scheme (which I think is correct or at least really common in the kafka examples I've seen so far), it ends up as an empty value in the config file.

I'm not sure if the host filter is needed, or if we would need to replace it with something else. I can patch if we can work out what the right thing is to do!

**Comment by derberg** [comment]
@lornajane thanks a lot for a well-described issue. I agree with you, haven't seen any example with scheme in the URL. Nevertheless because we already have a filter like [this](https://github.com/asyncapi/nodejs-template/blob/master/filters/all.js#L120) I suggest to fix by changing the filter than removing the filter entirely
