### ISSUE TITLE
Integrate asyncapi-validator in Nodejs templates

### ISSUE THREAD

**Issue by derberg** [asyncapi/nodejs-template#8]
@derberg commented on [Mon Mar 02 2020](https://github.com/asyncapi/generator/issues/234)

Reason:
Current Node templates nicely show what you can get from AsyncAPI file. You can generate an application that can work with Kafka or RabbitMQ, or others. When I play with those, there is one thing missing to make the templates nice, the message validation. Now you can send any message to the channel used by your application. Would be awesome to show that thanks to AsyncAPI with support of asyncapi-validator you can change that.

Description:
- Integrate https://www.npmjs.com/package/asyncapi-validator with the template
- Update docs and scratch note for release notes
- I'm wondering if it should be enabled by default or behind a parameter?

Something interesting for you @WaleedAshraf 😉 

---

@WaleedAshraf commented on [Mon Mar 02 2020](https://github.com/asyncapi/generator/issues/234#issuecomment-593330572)

🎉 Niceeee
I'd love to work on this, will try to join the next meeting and we can go from there. 👍 

---

@derberg commented on [Mon Mar 02 2020](https://github.com/asyncapi/generator/issues/234#issuecomment-593360366)

See ya tomorrow then!

**Comment by derberg** [comment]
@WaleedAshraf just pinging you so you know the location of the issue changed

**Comment by derberg** [comment]
video about the issue https://youtu.be/Iqs_2BiNEEo?t=1396

**Comment by gabrielclaudino** [comment]
Hey, I can help with this. 😄 Can you assign to me?

**Comment by KhudaDad414** [comment]
I want to work on this. @derberg any advice?

**Comment by derberg** [comment]
oh man, that would be fantastic! 

so the idea is that once you do `mqtt pub -t 'smartylighting/streetlights/1/0/event/{streetlightId}/lighting/measured' -h 'test.mosquitto.org' -m '{"id": 1, "lumens": "3", "sentAt": "2017-06-07T12:34:32.000Z"}'` the server doesn't process the message but logs an error that message is invalid as `lumens` should be integer.

@WaleedAshraf is the author of the validator so I hope that once you need some ideas on how to plug it in, he can help
