### ISSUE TITLE
Variables should not be shadowed

### ISSUE THREAD

**Issue by derberg** [asyncapi/nodejs-template#91]
It happens 3 times in `filters/all.js`

- https://sonarcloud.io/project/issues?id=asyncapi_nodejs-template&issues=AXSXW9Lo1vC5408yMwFu&open=AXSXW9Lo1vC5408yMwFu
- https://sonarcloud.io/project/issues?id=asyncapi_nodejs-template&issues=AXSXW9Lo1vC5408yMwFf&open=AXSXW9Lo1vC5408yMwFf
- https://sonarcloud.io/project/issues?id=asyncapi_nodejs-template&issues=AXSXW9Lo1vC5408yMwFb&open=AXSXW9Lo1vC5408yMwFb

**Comment by leonardomaier** [comment]
Hi @derberg, I'd be glad to help with this issue, can you assign me?

**Comment by leonardomaier** [comment]
@derberg done! please, check if the variable names make sense 😉

**Comment by ritik307** [comment]
@derberg is this issue still active? If so I would like to work on this

**Comment by derberg** [comment]
oh, sorry, this one is fixed and merged
